### PR TITLE
Fix incorrect readme.

### PR DESCRIPTION
**Pull request by wangzw**

### CODE REVIEW

**Comment by kyon0304** [comment]
hi

The change you made need this sdk to be published to [maven repository](https://oss.sonatype.org/), and we're working on it, thank you for your reminding, for now, I'm closing this pr.

**Comment by wangzw** [comment]
This pr also fix some bugs in the readme

**Comment by kyon0304** [comment]
Hi, wangzw

Sorry for may rashness, please commit again to exclude the <dependency> part, and I'll merge it.

**Comment by kyon0304** [comment]
Since we have update Readme file according to your reminder and conflict occurs,  I'm closing this pr.

Thanks again for your participation and we are looking forward to more of your pr.

**Pull request closed without merging**
